export let currencies = [
    {
        "country":"United Arab Emirates",
        "currency":"Dirham",
        "mnemonic":"AED"
    },
    {
        "country":"Albania",
        "currency":"Lek",
        "mnemonic":"ALL"
    },
    {
        "country":"Argentina",
        "currency":"Peso",
        "mnemonic":"ARS"
    },
    {
        "country":"Australia",
        "currency":"Dollar",
        "mnemonic":"AUD"
    },
    {
        "country":"Bangladesh",
        "currency":"Taka",
        "mnemonic":"BDT"
    },
    {
        "country":"Bulgaria",
        "currency":"Lev",
        "mnemonic":"BGN"
    },
    {
        "country":"Bahrain",
        "currency":"Dinar",
        "mnemonic":"BHD"
    },
    {
        "country":"Burundi",
        "currency":"Franc",
        "mnemonic":"BIF"
    },
    {
        "country":"Bolivia",
        "currency":"Boliviano",
        "mnemonic":"BOB"
    },
    {
        "country":"Brazil",
        "currency":"Real",
        "mnemonic":"BRL"
    },
    {
        "country":"Botswana",
        "currency":"Pula",
        "mnemonic":"BWP"
    },
    {
        "country":"Canada",
        "currency":"Dollar",
        "mnemonic":"CAD"
    },
    {
        "country":"Swiss",
        "currency":"Franc",
        "mnemonic":"CHF"
    },
    {
        "country":"Chile",
        "currency":"Peso",
        "mnemonic":"CLP"
    },
    {
        "country":"China",
        "currency":"Yuan",
        "mnemonic":"CNY"
    },
    {
        "country":"Colombia",
        "currency":"Peso",
        "mnemonic":"COP"
    },
    {
        "country":"Cape Verde",
        "currency":"Escudo",
        "mnemonic":"CVE"
    },
    {
        "country":"Czech",
        "currency":"Koruna",
        "mnemonic":"CZK"
    },
    {
        "country":"Denmark",
        "currency":"Krone",
        "mnemonic":"DKK"
    },
    {
        "country":"Dominican Republic",
        "currency":"Peso",
        "mnemonic":"DOP"
    },
    {
        "country":"Egypt",
        "currency":"Pound",
        "mnemonic":"EGP"
    },
    {
        "country":"Ethiopia",
        "currency":"Birr",
        "mnemonic":"ETB"
    },
    {
        "country":"Fiji",
        "currency":"Dollar",
        "mnemonic":"FJD"
    },
    {
        "country":"Britain",
        "currency":"Pound",
        "mnemonic":"GBP"
    },
    {
        "country":"Ghana",
        "currency":"Cedi",
        "mnemonic":"GHS"
    },
    {
        "country":"Gibralter",
        "currency":"Pound",
        "mnemonic":"GIP"
    },
    {
        "country":"Gambia",
        "currency":"Dalasi",
        "mnemonic":"GMD"
    },
    {
        "country":"Guinea",
        "currency":"Franc",
        "mnemonic":"GNF"
    },
    {
        "country":"Guatemala",
        "currency":"Quetzal",
        "mnemonic":"GTQ"
    },
    {
        "country":"Hungary",
        "currency":"Forint",
        "mnemonic":"HUF"
    },
    {
        "country":"Indonesia",
        "currency":"Rupiah",
        "mnemonic":"IDR"
    },
    {
        "country":"India",
        "currency":"Rupee",
        "mnemonic":"INR"
    },
    {
        "country":"Iceland",
        "currency":"Krona",
        "mnemonic":"ISK"
    },
    {
        "country":"Jordan",
        "currency":"Dinar",
        "mnemonic":"JOD"
    },
    {
        "country":"Japan",
        "currency":"yen",
        "mnemonic":"JPY"
    },
    {
        "country":"Kenya",
        "currency":"Shilling",
        "mnemonic":"KES"
    },
    {
        "country":"South Korea",
        "currency":"Won",
        "mnemonic":"KRW"
    },
    {
        "country":"Kuwait",
        "currency":"Dinar",
        "mnemonic":"KWD"
    },
    {
        "country":"Laos",
        "currency":"Kip",
        "mnemonic":"LAK"
    },
    {
        "country":"Sri Lanka",
        "currency":"Rupee",
        "mnemonic":"LKR"
    },
    {
        "country":"Morocco",
        "currency":"Dirham",
        "mnemonic":"MAD"
    },
    {
        "country":"Madagascar",
        "currency":"Ariary",
        "mnemonic":"MGA"
    },
    {
        "country":"Malawi",
        "currency":"Kwacha",
        "mnemonic":"MWK"
    },
    {
        "country":"Mexico",
        "currency":"Peso",
        "mnemonic":"MXN"
    },
    {
        "country":"Malaysia",
        "currency":"Ringgit",
        "mnemonic":"MYR"
    },
    {
        "country":"Mozambique",
        "currency":"Metical",
        "mnemonic":"MZN"
    },
    {
        "country":"Nigeria",
        "currency":"Naira",
        "mnemonic":"NGN"
    },
    {
        "country":"Norway",
        "currency":"Krone",
        "mnemonic":"NOK"
    },
    {
        "country":"Nepal",
        "currency":"Rupee",
        "mnemonic":"NPR"
    },
    {
        "country":"New Zealand",
        "currency":"Dollar",
        "mnemonic":"NZD"
    },
    {
        "country":"Oman",
        "currency":"Rial",
        "mnemonic":"OMR"
    },
    {
        "country":"Peru",
        "currency":"Sol",
        "mnemonic":"PEN"
    },
    {
        "country":"Philippines",
        "currency":"Peso",
        "mnemonic":"PHP"
    },
    {
        "country":"Pakistan",
        "currency":"Rupee",
        "mnemonic":"PKR"
    },
    {
        "country":"Poland",
        "currency":"Zloty",
        "mnemonic":"PLN"
    },
    {
        "country":"Paraguay",
        "currency":"Guarani",
        "mnemonic":"PYG"
    },
    {
        "country":"Qatar",
        "currency":"Riyal",
        "mnemonic":"QAR"
    },
    {
        "country":"Romania",
        "currency":"Leu",
        "mnemonic":"RON"
    },
    {
        "country":"Rwanda",
        "currency":"Franc",
        "mnemonic":"RWF"
    },
    {
        "country":"Saudi Arabia",
        "currency":"Riyal",
        "mnemonic":"SAR"
    },
    {
        "country":"Sweden",
        "currency":"Krona",
        "mnemonic":"SEK"
    },
    {
        "country":"Sierra Leone",
        "currency":"Leone",
        "mnemonic":"SLE"
    },
    {
        "country":"Suriname",
        "currency":"Dollar",
        "mnemonic":"SRD"
    },
    {
        "country":"Thailand",
        "currency":"Baht",
        "mnemonic":"THB"
    },
    {
        "country":"Tunisia",
        "currency":"Dinar",
        "mnemonic":"TND"
    },
    {
        "country":"Türkiye",
        "currency":"Lira",
        "mnemonic":"TRY"
    },
    {
        "country":"Taiwan",
        "currency":"Dollar",
        "mnemonic":"TWD"
    },
    {
        "country":"Tanzania",
        "currency":"Shilling",
        "mnemonic":"TZS"
    },
    {
        "country":"Uganda",
        "currency":"Shilling",
        "mnemonic":"UGX"
    },
    {
        "country":"United States of America",
        "currency":"Dollar",
        "mnemonic":"USD"
    },
    {
        "country":"Vietnam",
        "currency":"Dong",
        "mnemonic":"VND"
    },
    {
        "country":"Central Africa Republic CFA",
        "currency":"Franc",
        "mnemonic":"XAF"
    },
    {
        "country":"East Caribbean",
        "currency":"Dollar",
        "mnemonic":"XCD"
    },
    {
        "country":"West African CFA",
        "currency":"Franc",
        "mnemonic":"XOF"
    },
    {
        "country":"South Africa",
        "currency":"Rand",
        "mnemonic":"ZAR"
    },
    {
        "country":"Zambia",
        "currency":"Kwacha",
        "mnemonic":"ZMW"
    }
]