export let currencies = [
  { country: "Afghanistan", currency: "Afghan afghani", code: "AFN" },
  {
    country: "Akrotiri and Dhekelia (UK)",
    currency: "European euro",
    code: "EUR",
  },
  { country: "Albania", currency: "Albanian lek", code: "ALL" },
  { country: "Algeria", currency: "Algerian dinar", code: "DZD" },
  {
    country: "American Samoa (USA)",
    currency: "United States dollar",
    code: "USD",
  },
  { country: "Angola", currency: "Angolan kwanza", code: "AOA" },
  { country: "Anguilla (UK)", currency: "East Caribbean dollar", code: "XCD" },
  { country: "Argentina", currency: "Argentine peso", code: "ARS" },
  { country: "Armenia", currency: "Armenian dram", code: "AMD" },
  { country: "Aruba (Netherlands)", currency: "Aruban florin", code: "AWG" },
  {
    country: "Ascension Island (UK)",
    currency: "Saint Helena pound",
    code: "SHP",
  },
  { country: "Australia", currency: "Australian dollar", code: "AUD" },
  { country: "Azerbaijan", currency: "Azerbaijan manat", code: "AZN" },
  { country: "Bahamas", currency: "Bahamian dollar", code: "BSD" },
  { country: "Bahrain", currency: "Bahraini dinar", code: "BHD" },
  { country: "Bangladesh", currency: "Bangladeshi taka", code: "BDT" },
  { country: "Barbados", currency: "Barbadian dollar", code: "BBD" },
  { country: "Belarus", currency: "Belarusian ruble", code: "BYN" },
  { country: "Belize", currency: "Belize dollar", code: "BZD" },
  { country: "Benin", currency: "West African CFA franc", code: "XOF" },
  { country: "Bermuda (UK)", currency: "Bermudian dollar", code: "BMD" },
  { country: "Bhutan", currency: "Bhutanese ngultrum", code: "BTN" },
  { country: "Bolivia", currency: "Bolivian boliviano", code: "BOB" },
  {
    country: "Bosnia and Herzegovina",
    currency: "Bosnia and Herzegovina convertible mark",
    code: "BAM",
  },
  { country: "Botswana", currency: "Botswana pula", code: "BWP" },
  { country: "Brazil", currency: "Brazilian real", code: "BRL" },
  { country: "Brunei", currency: "Brunei dollar", code: "BND" },
  { country: "Burundi", currency: "Burundi franc", code: "BIF" },
  { country: "Cabo Verde", currency: "Cabo Verdean escudo", code: "CVE" },
  { country: "Cambodia", currency: "Cambodian riel", code: "KHR" },
  { country: "Cameroon", currency: "Central African CFA franc", code: "XAF" },
  { country: "Canada", currency: "Canadian dollar", code: "CAD" },
  {
    country: "Cayman Islands (UK)",
    currency: "Cayman Islands dollar",
    code: "KYD",
  },
  {
    country: "Chatham Islands (New Zealand)",
    currency: "New Zealand dollar",
    code: "NZD",
  },
  { country: "Chile", currency: "Chilean peso", code: "CLP" },
  { country: "China", currency: "Chinese Yuan Renminbi", code: "CNY" },
  { country: "Colombia", currency: "Colombian peso", code: "COP" },
  { country: "Comoros", currency: "Comorian franc", code: "KMF" },
  {
    country: "Congo, Democratic Republic of the",
    currency: "Congolese franc",
    code: "CDF",
  },
  {
    country: "Cook Islands (New Zealand)",
    currency: "Cook Islands dollar",
    code: "none",
  },
  { country: "Costa Rica", currency: "Costa Rican colon", code: "CRC" },
  { country: "Cuba", currency: "Cuban peso", code: "CUP" },
  {
    country: "Curacao (Netherlands)",
    currency: "Netherlands Antillean guilder",
    code: "ANG",
  },
  { country: "Czechia", currency: "Czech koruna", code: "CZK" },
  { country: "Denmark", currency: "Danish krone", code: "DKK" },
  { country: "Djibouti", currency: "Djiboutian franc", code: "DJF" },
  { country: "Dominican Republic", currency: "Dominican peso", code: "DOP" },
  { country: "Egypt", currency: "Egyptian pound", code: "EGP" },
  { country: "Eritrea", currency: "Eritrean nakfa", code: "ERN" },
  { country: "Eswatini", currency: "Swazi lilangeni", code: "SZL" },
  { country: "Ethiopia", currency: "Ethiopian birr", code: "ETB" },
  {
    country: "Falkland Islands (UK)",
    currency: "Falkland Islands pound",
    code: "FKP",
  },
  {
    country: "Faroe Islands (Denmark)",
    currency: "Faroese krona",
    code: "none",
  },
  { country: "Fiji", currency: "Fijian dollar", code: "FJD" },
  { country: "French Polynesia (France)", currency: "CFP franc", code: "XPF" },
  { country: "Gambia", currency: "Gambian dalasi", code: "GMD" },
  { country: "Georgia", currency: "Georgian lari", code: "GEL" },
  { country: "Ghana", currency: "Ghanaian cedi", code: "GHS" },
  { country: "Gibraltar (UK)", currency: "Gibraltar pound", code: "GIP" },
  { country: "Guatemala", currency: "Guatemalan quetzal", code: "GTQ" },
  { country: "Guernsey (UK)", currency: "Guernsey Pound", code: "GGP" },
  { country: "Guinea", currency: "Guinean franc", code: "GNF" },
  { country: "Guyana", currency: "Guyanese dollar", code: "GYD" },
  { country: "Haiti", currency: "Haitian gourde", code: "HTG" },
  { country: "Honduras", currency: "Honduran lempira", code: "HNL" },
  { country: "Hong Kong (China)", currency: "Hong Kong dollar", code: "HKD" },
  { country: "Hungary", currency: "Hungarian forint", code: "HUF" },
  { country: "Iceland", currency: "Icelandic krona", code: "ISK" },
  { country: "India", currency: "Indian rupee", code: "INR" },
  { country: "Indonesia", currency: "Indonesian rupiah", code: "IDR" },
  {
    country: "International Monetary Fund (IMF)",
    currency: "SDR (Special Drawing Right)",
    code: "XDR",
  },
  { country: "Iran", currency: "Iranian rial", code: "IRR" },
  { country: "Iraq", currency: "Iraqi dinar", code: "IQD" },
  { country: "Isle of Man (UK)", currency: "Manx pound", code: "IMP" },
  { country: "Israel", currency: "Israeli new shekel", code: "ILS" },
  { country: "Jamaica", currency: "Jamaican dollar", code: "JMD" },
  { country: "Japan", currency: "Japanese yen", code: "JPY" },
  { country: "Jersey (UK)", currency: "Jersey pound", code: "JEP" },
  { country: "Jordan", currency: "Jordanian dinar", code: "JOD" },
  { country: "Kazakhstan", currency: "Kazakhstani tenge", code: "KZT" },
  { country: "Kenya", currency: "Kenyan shilling", code: "KES" },
  { country: "Kuwait", currency: "Kuwaiti dinar", code: "KWD" },
  { country: "Kyrgyzstan", currency: "Kyrgyzstani som", code: "KGS" },
  { country: "Laos", currency: "Lao kip", code: "LAK" },
  { country: "Lebanon", currency: "Lebanese pound", code: "LBP" },
  { country: "Lesotho", currency: "Lesotho loti", code: "LSL" },
  { country: "Liberia", currency: "Liberian dollar", code: "LRD" },
  { country: "Libya", currency: "Libyan dinar", code: "LYD" },
  { country: "Liechtenstein", currency: "Swiss franc", code: "CHF" },
  { country: "Macau (China)", currency: "Macanese pataca", code: "MOP" },
  { country: "Madagascar", currency: "Malagasy ariary", code: "MGA" },
  { country: "Malawi", currency: "Malawian kwacha", code: "MWK" },
  { country: "Malaysia", currency: "Malaysian ringgit", code: "MYR" },
  { country: "Maldives", currency: "Maldivian rufiyaa", code: "MVR" },
  { country: "Mauritania", currency: "Mauritanian ouguiya", code: "MRU" },
  { country: "Mauritius", currency: "Mauritian rupee", code: "MUR" },
  { country: "Mexico", currency: "Mexican peso", code: "MXN" },
  { country: "Moldova", currency: "Moldovan leu", code: "MDL" },
  { country: "Mongolia", currency: "Mongolian tugrik", code: "MNT" },
  { country: "Morocco", currency: "Moroccan dirham", code: "MAD" },
  { country: "Mozambique", currency: "Mozambican metical", code: "MZN" },
  { country: "Myanmar", currency: "Myanmar kyat", code: "MMK" },
  { country: "Namibia", currency: "Namibian dollar", code: "NAD" },
  { country: "Nepal", currency: "Nepalese rupee", code: "NPR" },
  { country: "Nicaragua", currency: "Nicaraguan cordoba", code: "NIO" },
  { country: "Nigeria", currency: "Nigerian naira", code: "NGN" },
  { country: "North Korea", currency: "North Korean won", code: "KPW" },
  { country: "North Macedonia", currency: "Macedonian denar", code: "MKD" },
  { country: "Norway", currency: "Norwegian krone", code: "NOK" },
  { country: "Oman", currency: "Omani rial", code: "OMR" },
  { country: "Pakistan", currency: "Pakistani rupee", code: "PKR" },
  {
    country: "Papua New Guinea",
    currency: "Papua New Guinean kina",
    code: "PGK",
  },
  { country: "Paraguay", currency: "Paraguayan guarani", code: "PYG" },
  { country: "Peru", currency: "Peruvian sol", code: "PEN" },
  { country: "Philippines", currency: "Philippine peso", code: "PHP" },
  { country: "Poland", currency: "Polish zloty", code: "PLN" },
  { country: "Qatar", currency: "Qatari riyal", code: "QAR" },
  { country: "Romania", currency: "Romanian leu", code: "RON" },
  { country: "Russia", currency: "Russian ruble", code: "RUB" },
  { country: "Rwanda", currency: "Rwandan franc", code: "RWF" },
  { country: "Samoa", currency: "Samoan tala", code: "WST" },
  {
    country: "Sao Tome and Principe",
    currency: "Sao Tome and Principe dobra",
    code: "STN",
  },
  { country: "Saudi Arabia", currency: "Saudi Arabian riyal", code: "SAR" },
  { country: "Serbia", currency: "Serbian dinar", code: "RSD" },
  { country: "Seychelles", currency: "Seychellois rupee", code: "SCR" },
  { country: "Sierra Leone", currency: "Sierra Leonean leone", code: "SLE" },
  { country: "Singapore", currency: "Singapore dollar", code: "SGD" },
  {
    country: "Solomon Islands",
    currency: "Solomon Islands dollar",
    code: "SBD",
  },
  { country: "Somalia", currency: "Somali shilling", code: "SOS" },
  { country: "South Africa", currency: "South African rand", code: "ZAR" },
  {
    country: "South Georgia Island (UK)",
    currency: "Pound sterling",
    code: "GBP",
  },
  { country: "South Korea", currency: "South Korean won", code: "KRW" },
  { country: "South Sudan", currency: "South Sudanese pound", code: "SSP" },
  { country: "Sri Lanka", currency: "Sri Lankan rupee", code: "LKR" },
  { country: "Sudan", currency: "Sudanese pound", code: "SDG" },
  { country: "Suriname", currency: "Surinamese dollar", code: "SRD" },
  { country: "Sweden", currency: "Swedish krona", code: "SEK" },
  { country: "Syria", currency: "Syrian pound", code: "SYP" },
  { country: "Taiwan", currency: "New Taiwan dollar", code: "TWD" },
  { country: "Tajikistan", currency: "Tajikistani somoni", code: "TJS" },
  { country: "Tanzania", currency: "Tanzanian shilling", code: "TZS" },
  { country: "Thailand", currency: "Thai baht", code: "THB" },
  { country: "Tonga", currency: "Tongan pa’anga", code: "TOP" },
  {
    country: "Trinidad and Tobago",
    currency: "Trinidad and Tobago dollar",
    code: "TTD",
  },
  { country: "Tunisia", currency: "Tunisian dinar", code: "TND" },
  { country: "Turkey", currency: "Turkish lira", code: "TRY" },
  { country: "Turkmenistan", currency: "Turkmen manat", code: "TMT" },
  { country: "Uganda", currency: "Ugandan shilling", code: "UGX" },
  { country: "Ukraine", currency: "Ukrainian hryvnia", code: "UAH" },
  { country: "United Arab Emirates", currency: "UAE dirham", code: "AED" },
  { country: "Uruguay", currency: "Uruguayan peso", code: "UYU" },
  { country: "Uzbekistan", currency: "Uzbekistani som", code: "UZS" },
  { country: "Vanuatu", currency: "Vanuatu vatu", code: "VUV" },
  { country: "Venezuela", currency: "Venezuelan bolivar", code: "VES" },
  { country: "Vietnam", currency: "Vietnamese dong", code: "VND" },
  { country: "Yemen", currency: "Yemeni rial", code: "YER" },
  { country: "Zambia", currency: "Zambian kwacha", code: "ZMW" },
  { country: "Zimbabwe", currency: "Zimbabwe gold", code: "ZWG" },
];
